spring:
  security:
    oauth2:
      resourceserver:
        issuer-uri: http://localhost:8080/realms/pgm
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/pgm/protocol/openid-connect/certs"
  #        opaquetoken:
#          client-id: pgm_manager
#          client-secret: 7DsSZMk3h1CrFzqPlAHyqsQa3e46hXZ9
#          introspection-uri: http://localhost:8080/realms/pgm/protocol/openid-connect/token/introspect
  #        jwt:


  datasource:
    url: jdbc:mariadb://localhost:3306/api_oauth2
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 8081
