spring:
  security:
    oauth2:
      resourceserver:
        issuer-uri: http://localhost:8080/realms/pgm
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/pgm/protocol/openid-connect/certs"

  datasource:
    url: jdbc:mariadb://localhost:3306/api_oauth2
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  swagger-ui:
    oauth:
      client-id: pgm_manager
      client-secret: 7DsSZMk3h1CrFzqPlAHyqsQa3e46hXZ9

server:
  port: 8081
